name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - name: install uv
        run: pip install uv
      - name: install dependency
        run: uv sync
      - name: run test
        run: uv run poe test
