name: lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install poetry
        run: pip install poetry
      - name: install dependency
        run: poetry install --no-interaction
      - name: run test
        run: poetry run pytest
